# Generated by Django 4.0 on 2023-06-06 17:43

from django.db import migrations
import ticket_manager.user_manager


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', ticket_manager.user_manager.UserManager()),
            ],
        ),
    ]
