# Generated by Django 4.0 on 2023-06-07 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_manager', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='users',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='site',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='ticket_manager.user'),
        ),
    ]
